- hosts: workers
  remote_user: "{{ k8s_user }}"
  become: true
  become_method: sudo
  become_user: root
  gather_facts: true
  connection: ssh

  vars_files:
    - vars/default.yml    

  tasks:

   - name: Copy join command to worker nodes.
     become: true
     become_method: sudo
     become_user: root
     copy:
       src: /tmp/kubernetes_join_command
       dest: /tmp/kubernetes_join_command
       mode: 0777   

   - name: Join the Worker nodes with the master.
     become: true
     become_method: sudo
     become_user: root
     command: sh /tmp/kubernetes_join_command
     register: joined_or_not

   - debug:
       msg: "{{ joined_or_not.stdout }}"
