- hosts: masters
  become: true
  become_method: sudo
  become_user: root
  gather_facts: true
  connection: ssh

  vars_files:
    - vars/default.yml

  tasks:
    - name: Intilizing Kubernetes Cluster
      command: kubeadm init
      run_once: true

    - pause: seconds=30

    - name: Create directory for kube config.
      become_user: "{{ k8s_user }}"
      become_method: sudo
      become: true
      file:
        path: /home/{{ k8s_user }}/.kube
        state: directory
        owner: "{{ k8s_user }}"
        group: "{{ k8s_user }}"
        mode: 0755

    - name: Copy /etc/kubernetes/admin.conf to user's home directory /home/{{ k8s_user }}/.kube/config.
      become_user: root
      become_method: sudo
      become: true
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/{{ k8s_user }}/.kube/config
        remote_src: yes
        owner: "{{ k8s_user }}"
        group: "{{ k8s_user }}"
        mode: "0644"

    - pause: seconds=10

    - name: Remove the cache directory.
      become_user: "{{ k8s_user }}"
      become_method: sudo
      become: true
      file:
        path: /home/{{ k8s_user }}/.kube/cache
        state: absent

    - pause: seconds=30

    - name: Create Pod Network & RBAC.
      become_user: "{{ k8s_user }}"
      become: true
      command: "{{ item }}"
      with_items:
        - kubectl apply -f {{ pod_network_manifest_file }}
        # - kubectl apply -f {{ rbac_manifest_file }}

    - pause: seconds=30

    - name: Get the token for joining the nodes with Kuberentes master.
      shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command

    - debug:
        msg: "{{ kubernetes_join_command.stdout }}"

    - name: Copy join command to local file.
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777

    - name: Configure kubectl command auto-completion.
      lineinfile:
        dest: /home/{{ k8s_user }}/.bashrc
        line: 'source <(kubectl completion bash)'
        insertafter: EOF
